version: '3.1'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qWmp6fphJ2pEsgVM
      MYSQL_DATABASE: car_booking
      MYSQL_USER: car_booking
      MYSQL_PASSWORD: mgCnv3mEBnj4fBpF
    ports:
      - 3306:3306